# see: https://github.com/nanxiaobei/hugo-paper/blob/main/exampleSite/config.toml

title = 'Toughiculties'
baseURL = 'https://toughiculties.com/'

author = "Nicholas Zwart"
copyright = "Copyright © 2016–2022, Nicholas Zwart; all rights reserved."

paginate = 5

languageCode = 'en'
DefaultContentLanguage = "en"
enableInlineShortcodes = true

# prevent build failures when using Hugo's Instagram shortcode due to deprecated Instagram API.
# See https://github.com/gohugoio/hugo/issues/7228#issuecomment-714490456
ignoreErrors = ["error-remote-getjson"]

googleAnalytics = "UA-76185171-1"
disqusShortname = "nckz"
enableRobotsTXT = true

theme = "hugo-paper"

# [menu]
#  [[menu.main]]
#    identifier = "about"
#    name = "About"
#    url = "/about/"
#    weight = 10

[params]
  github = "nckz"
  # twitter = ""
  # instagram = ""

[taxonomies]
  category = "categories"
  tag = "tags"
  series = "series"
